name: Testes de Comportamento

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  behave-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instala dependências
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb firefox-esr curl
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install behave splinter selenium flask

    - name: Inicia o servidor Flask (em background)
      run: |
        nohup xvfb-run -a python app/app.py > flask.log 2>&1 &

    - name: Espera o servidor iniciar (até 30s)
      run: |
        for i in {1..30}; do
          if curl -s http://localhost:5000/login > /dev/null; then
            echo "Servidor iniciado com sucesso."
            break
          fi
          echo "Aguardando servidor iniciar..."
          sleep 1
        done

    - name: Executa os testes Behave
      run: |
        behave features/
