name: Testes de Comportamento

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  behave-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instala dependências Python
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip xvfb libgtk-3-0 libdbus-glib-1-2
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install behave splinter selenium flask

    - name: Instala Firefox e Geckodriver
      run: |
        # Baixa e instala o geckodriver
        wget -q https://github.com/mozilla/geckodriver/releases/download/v0.32.0/geckodriver-v0.32.0-linux64.tar.gz
        tar -xzf geckodriver-v0.32.0-linux64.tar.gz
        sudo mv geckodriver /usr/local/bin

        # Baixa e instala o Firefox estável
        wget -q https://download.mozilla.org/?product=firefox-112.0-SSL&os=linux64&lang=pt-BR -O firefox.tar.bz2
        tar -xjf firefox.tar.bz2
        sudo mv firefox /opt/firefox
        sudo ln -s /opt/firefox/firefox /usr/local/bin/firefox

    - name: Inicia o servidor Flask (em background)
      run: |
        nohup xvfb-run -a python app/app.py > flask.log 2>&1 &

    - name: Espera o servidor iniciar (até 30s)
      run: |
        for i in {1..30}; do
          if curl -s http://localhost:5000/login > /dev/null; then
            echo "Servidor iniciado com sucesso."
            break
          fi
          echo "Aguardando servidor iniciar..."
          sleep 1
        done

    - name: Executa os testes Behave
      run: |
        behave features/
