name: Testes com Behave e Splinter

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out o código
        uses: actions/checkout@v2
        
      - name: Instalar dependências
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-dev python3-venv
          pip install -r requirements.txt

      - name: Baixar o GeckoDriver
        run: |
          curl -L https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz -o geckodriver.tar.gz
          tar -xvzf geckodriver.tar.gz
          sudo mv geckodriver /usr/local/bin/

      - name: Executar testes
        run: |
          pytest --maxfail=1 --disable-warnings -q
