name: Testes com Behave e Splinter

on:
  push:
    branches:
      - main  # Rodar os testes no push para a branch main

jobs:
  build:
    runs-on: ubuntu-latest  # Ambiente Ubuntu no GitHub Actions
    
    steps:
      - name: Check out o código
        uses: actions/checkout@v2  # Faz o checkout do repositório
        
      - name: Instalar dependências do sistema
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-dev python3-venv  # Instalar pacotes necessários
          pip install -r requirements.txt  # Instalar as dependências do Python

      - name: Baixar e configurar o GeckoDriver
        run: |
          # Baixar o GeckoDriver do GitHub
          curl -L https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz -o geckodriver.tar.gz
          
          # Extrair o arquivo baixado
          tar -xvzf geckodriver.tar.gz
          
          # Mover o geckodriver para o diretório global
          sudo mv geckodriver /usr/local/bin/

      - name: Verificar arquivos de teste
        run: |
          # Verifica o diretório onde os testes estão
          ls -R  # Lista recursivamente os arquivos e diretórios para garantir que os testes estão no lugar certo

      - name: Executar os testes com pytest
        run: |
          # Rodar os testes com pytest
          pytest --maxfail=1 --disable-warnings -q
