name: Run Tests with Behave and pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checar código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Instalar dependências
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verificar estrutura de diretórios
      run: |
        ls -R  # Lista recursivamente os arquivos e diretórios

    - name: Rodar testes com Behave e pytest
      run: |
        # Rodar testes com Behave
        behave features/login.feature --tags=@login
        
        # Rodar os testes com pytest
        pytest features/steps/login_steps.py --maxfail=1 --disable-warnings -v
